sonar.projectKey=advprog-2026-A17-project_bidmart-frontend
sonar.organization=advprog-2026-a17-project
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=.
sonar.test.inclusions=*.contract.test.mjs
sonar.exclusions=dist/**,node_modules/**,coverage/**,artifacts/**
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S7781
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
